name: Build Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - run: pnpm install
      - run: pnpm build
      - run: pnpm test