name: Pre-Publish tagged Pull Requests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-release:
    if: contains(github.event.pull_request.labels.*.name, 'pre-release')
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable latestcorepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies
        run: pnpm install

      - name: Pnpm Build
        run: pnpm build

      - name: Pre publish
        run: pnpx pkg-pr-new publish
