name: Pre-Publish tagged Pull Requests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-release:
    if: contains(github.event.pull_request.labels.*.name, 'pre-release')
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Pnpm Build
        run: pnpm build

      - name: Pre publish
        run: pnpm pkg-pr-new publish
